// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCongTacVien.Data;

#nullable disable

namespace QuanLyCongTacVien.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509033317_AddIsDeleteProperty")]
    partial class AddIsDeleteProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("QuanLyCongTacVien.Models.CongTacVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChuyenNganhDaoTao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DanToc")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DanhSachLuuTruGiayTo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChiThuongTru")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DienThoaiDiDong")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DienThoaiNhaRieng")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonViCongTac")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCaNhan")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhThucDaoTao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoVaTen")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HocHam")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HocVi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiHopDongNhomDichVu")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaNhanSu")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NamTotNghiep")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayCapBang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayVaoTruong")
                        .HasColumnType("TEXT");

                    b.Property<string>("NgoaiNguChinh")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiOHienNay")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiSinh")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("PhanTramTinhThue")
                        .HasColumnType("REAL");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoCMND")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaiKhoaBoMon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenGoiKhac")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TonGiao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrinhDoNgoaiNguChinh")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrinhDoTinHoc")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrinhDoVanHoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TruongDaoTao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CongTacVien");
                });
#pragma warning restore 612, 618
        }
    }
}
