// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCongTacVien.DAO;

#nullable disable

namespace QuanLyCongTacVien.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420093826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("QuanLyCongTacVien.DTO.CongTacVien", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCCD")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaQuanLy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuocTich")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.ToTable("CongTacViens");
                });

            modelBuilder.Entity("QuanLyCongTacVien.DTO.QuanLyHopDongCongTacVien", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaQuanLy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHopDong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.ToTable("HopDongs");
                });
#pragma warning restore 612, 618
        }
    }
}
